function(_uploader_trim input output_var)
    string(REGEX REPLACE "^[ \t\r\n]+" "" _tmp "${input}")
    string(REGEX REPLACE "[ \t\r\n]+$" "" _tmp "${_tmp}")
    set(${output_var} "${_tmp}" PARENT_SCOPE)
endfunction()

function(load_defaults_from_conf path)
    if (NOT EXISTS "${path}")
        message(FATAL_ERROR "uploader.conf not found at: ${path}")
    endif()

    file(STRINGS "${path}" _lines)
    set(_excludes "")

    foreach(_line IN LISTS _lines)
        _uploader_trim("${_line}" _trimmed)
        if (_trimmed STREQUAL "")
            continue()
        endif()
        if (_trimmed MATCHES "^[#;]")
            continue()
        endif()
        string(FIND "${_trimmed}" "=" _eq_pos)
        if (_eq_pos EQUAL -1)
            continue()
        endif()
        string(SUBSTRING "${_trimmed}" 0 ${_eq_pos} _key)
        math(EXPR _value_pos "${_eq_pos} + 1")
        string(SUBSTRING "${_trimmed}" ${_value_pos} -1 _value)
        _uploader_trim("${_key}" _key)
        _uploader_trim("${_value}" _value)
        if (_key STREQUAL "")
            continue()
        endif()

        string(REGEX REPLACE "^\xEF\xBB\xBF" "" _key "${_key}")
        string(TOLOWER "${_key}" _key_lower)
        string(TOLOWER "${_value}" _value_lower)
        if (_value_lower STREQUAL "test")
            continue()
        endif()

        if (_key_lower STREQUAL "email")
            set(CONF_EMAIL "${_value}" PARENT_SCOPE)
        elseif (_key_lower STREQUAL "app_password" OR _key_lower STREQUAL "app-password")
            set(CONF_APP_PASSWORD "${_value}" PARENT_SCOPE)
        elseif (_key_lower STREQUAL "source")
            set(CONF_SOURCE "${_value}" PARENT_SCOPE)
        elseif (_key_lower STREQUAL "remote")
            set(CONF_REMOTE "${_value}" PARENT_SCOPE)
        elseif (_key_lower STREQUAL "base_url" OR _key_lower STREQUAL "base-url")
            set(CONF_BASE_URL "${_value}" PARENT_SCOPE)
        elseif (_key_lower STREQUAL "threads")
            set(CONF_THREADS "${_value}" PARENT_SCOPE)
        elseif (_key_lower STREQUAL "compare")
            set(CONF_COMPARE "${_value}" PARENT_SCOPE)
        elseif (_key_lower STREQUAL "dry_run" OR _key_lower STREQUAL "dry-run")
            set(CONF_DRY_RUN "${_value}" PARENT_SCOPE)
        elseif (_key_lower STREQUAL "exclude")
            list(APPEND _excludes "${_value}")
        endif()
    endforeach()

    if (_excludes)
        list(JOIN _excludes ";" _excludes_joined)
        set(CONF_EXCLUDES "${_excludes_joined}" PARENT_SCOPE)
    endif()
endfunction()
